### ISSUE TITLE
证书文件未正常下载到本地

### ISSUE THREAD

**Issue by 1194162880** [EliasZzz/CertificateDownloader#22]
参数内容填写正常，执行java -jar 后下载地址指向本地地址，但是未生成pem文件。
-----BEGIN CERTIFICATE-----
****************************************************
-----END CERTIFICATE-----
[main] WARN com.wechat.pay.contrib.apache.httpclient.auth.WechatPay2Validator - For input string: "PUB"
=== validate failed ===
=== download done ===

**Comment by youfeed** [comment]
首次和二次不一样得,扒你命令贴出来
```
java -jar CertificateDownloader.jar -k PrlbgF6S**** -m 16818**** -f ./apiclient_key.pem -s 7C9C6954D13014196807****** -o ./
```

**Comment by qianshanlaikan** [comment]
同样的问题，参数填写正确，未正常下载
=== download begin ===
body:{"data":[]}
[main] WARN com.wechat.pay.contrib.apache.httpclient.auth.WechatPay2Validator - For input string: "PUB"
=== validate failed ===
=== download done ===

执行命令如下
java -jar CertificateDownloader.jar -k ****2124343 -m 1551**** -f ./apiclient_key.pem -s 2797A1ED0E9**** -o ./

**Comment by youfeed** [comment]
提示你验证序列号对不上 
到后台 API 那获取API序列号

**Comment by qianshanlaikan** [comment]
已经试过申请一个新的API证书，还是报相同错误

> 提示你验证序列号对不上 到后台 API 那获取API序列号

**Comment by qianshanlaikan** [comment]
> 提示你验证序列号对不上 到后台 API 那获取API序列号

证书序列号匹配不正确，报的是另外一个错误

=== download begin ===
[main] ERROR com.wechat.pay.contrib.apache.httpclient.SignatureExec - 应答的状态码不为200-299。status code[401] request headers[[Accept: application/json, Authorization: WECHATPAY2-SHA256-RSA2048 mchid="1551832001",nonce_str="1pYcZOfPFTYms5pWFacDAVpQeV9pVWXp",timestamp="1732096732",serial_no="615BDEC3DBDCC59FE55F13F7D688B939CF7D8FD5",signature="AdsCDPgJogYgKDZ2IIKdEY3fbAMoiE0/P7pQwUTKEUa99ubObiConkOFjfuT2VI/POA0Kx6LdMuBhmU0J/n4qv2d7Nh787+ndgv+PC7g99yuxwg+6EihqNhlIAFojY6VLCHmRarqsPgrJiSsjKGGhjLnqhH6/ZxUHEVemZX+Uedxz2CtPV7intWVYzHHOX5rGNm9BRdgWjI+lQUhwPWk0uEBJ3G44fECVk0qDgLyugaS42jSeul8w/5PCboda91fLifo0bKt5o36wQ8q2PS4s84pLa2c8Gz65y+xQC7SmlBHKhIcUylW4NFOo5Q+0RDh0r6agiqN6gOlo5lFazmT+A==", Host: api.mch.weixin.qq.com, Connection: Keep-Alive, User-Agent: WechatPay-Apache-HttpClient/null (Windows 10/10.0) Java/11.0.17, Accept-Encoding: gzip,deflate]]
download failed,resp code=401,body={"code":"SIGN_ERROR","detail":{"detail":{"issue":"sign not match"},"field":"signature","location":"authorization","sign_information":{"method":"GET","sign_message_length":66,"truncated_sign_message":"GET\n/v3/certificates\n1732096732\n1pYcZOfPFTYms5pWFacDAVpQeV9pVWXp\n\n","url":"/v3/certificates"}},"message":"错误的签名，验签失败"}
java.io.IOException: request failed
        at com.elias.CertificateDownloader.downloadCertificate(CertificateDownloader.java:104)
        at com.elias.CertificateDownloader.run(CertificateDownloader.java:65)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:2172)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:2559)
        at picocli.CommandLine.run(CommandLine.java:3017)
        at picocli.CommandLine.run(CommandLine.java:2954)
        at com.elias.CertificateDownloader.main(CertificateDownloader.java:153)

**Comment by Djs37** [comment]
一样的问题, 和序列号估计没关系, 我故意改错序列号, 会提示序列号错误, 但用正确的序列号会显示
```
=== download begin ===
body:{"data":[]}
[main] WARN com.wechat.pay.contrib.apache.httpclient.auth.WechatPay2Validator - For input string: "PUB"
=== validate failed ===
=== download done ===
```

序列号错误是这样的
```
download failed,resp code=401,body={"code":"SIGN_ERROR","message":"商户证书序列号有误。请使用签名私钥匹配的证书序列号"}
java.io.IOException: request failed
```
不知道怎么解决
